server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: user-talentportal
        uri: lb://user-talentportal
        predicates:
          - Path=/talentportal/**
      - id: jobseeker-service
        uri: lb://jobseeker-service
        predicates:
          - Path=/jobseeker/**   
      - id: Employer-service
        uri: lb://Employer-service
        predicates:
          - Path=/Employer/**
      - id: USER-APP
        uri: lb://USER-APP
        predicates:
          - Path=/devforum/**
      - id: FORUM-APP
        uri: lb://FORUM-APP
        predicates:
          - Path=/devforum_forum/**
      - id: IM-ADMIN
        uri: lb://IM-ADMIN
        predicates:
          - Path=/interview-management/admin/**
      - id: IM-PANEL
        uri: lb://IM-PANEL
        predicates:
          - Path=/interview-management/panel/**
      - id: IM-USER
        uri: lb://IM-USER
        predicates:
          - Path=/interview-management/user/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"      

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
